server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mini_project
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false